name: daily-task

on:
  
  push: # push触发
    branches: [ main ]
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: '10 1-15/2 * * *' # cron表达式，Actions时区是UTC时间，所以要往前推8个小时(4-23)
    

jobs:
  daily-task:
    if: github.event.repository.owner.id == github.event.sender.id

    env:
      ENABLE_52POJIE: ${{secrets.ENABLE_52POJIE}}
      ENABLE_BILIBILI: ${{secrets.ENABLE_BILIBILI}}
      ENABLE_IQIYI: ${{secrets.ENABLE_IQIYI}}
      ENABLE_UNICOM: ${{secrets.ENABLE_UNICOM}}
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12]
        node-registry: ['https://registry.npmjs.org']

    steps:
    
    # 检出
    - name: Checkout
      uses: actions/checkout@v2
      
    # 设置服务器时区为东八区 
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: ${{ matrix.node-registry }}

    - name: Get npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"

    - name: restore npm cache
      uses: actions/cache@v2
      id: use-npm-cache
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: restore npm dependencies
      uses: actions/cache@v2
      id: use-npm-depends
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-depends-${{ hashFiles('**/package-lock.json') }}

    - name: restore task cache
      uses: actions/cache@v2
      id: use-task-cache
      with:
        path: |
          /home/runner/.AutoSignMachine
        key: ${{ runner.os }}-task-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      if: steps.use-npm-cache.outputs.cache-hit != 'true' || steps.use-npm-depends.outputs.cache-hit != 'true'
      run: npm install
       

    # 运行 unicom 签到任务
    - name: WYL
      if: ${{ env.ENABLE_UNICOM }}
      env:
        user: ${{secrets.HM1}}
        password: ${{secrets.MM1}}
        appid: ${{secrets.appid}}
      run: node index.js unicom --user=${user} --password=${password} --appid=${appid} ----tryrun
      
    - name: LYX
      if: ${{ env.ENABLE_UNICOM }}
      env:
        user: ${{secrets.HM2}}
        password: ${{secrets.MM2}}
        appid: ${{secrets.appid}}
      run: node index.js unicom --user=${user} --password=${password} --appid=${appid} ----tryrun
      
     - name: CZC
      if: ${{ env.ENABLE_UNICOM }}
      env:
        user: ${{secrets.HM3}}
        password: ${{secrets.MM}}
        appid: ${{secrets.appid}}
      run: node index.js unicom --user=${user} --password=${password} --appid=${appid} ----tryrun
      
     - name: CZR2
      if: ${{ env.ENABLE_UNICOM }}
      env:
        user: ${{secrets.HM4}}
        password: ${{secrets.MM}}
        appid: ${{secrets.appid}}
      run: node index.js unicom --user=${user} --password=${password} --appid=${appid} ----tryrun
      
     - name: CGq
      if: ${{ env.ENABLE_UNICOM }}
      env:
        user: ${{secrets.HM5}}
        password: ${{secrets.MM}}
        appid: ${{secrets.appid}}
      run: node index.js unicom --user=${user} --password=${password} --appid=${appid} ----tryrun
      

